#!/bin/bash

echo "🔧 Setting up Google OAuth for development..."

echo ""
echo "📋 Follow these steps to set up Google OAuth:"
echo ""
echo "1. Go to https://console.cloud.google.com/"
echo "2. Create a new project or select existing one"
echo "3. Enable Google+ API:"
echo "   - APIs & Services > Library"
echo "   - Search 'Google+ API'"
echo "   - Click Enable"
echo ""
echo "4. Create OAuth Credentials:"
echo "   - APIs & Services > Credentials"
echo "   - Create Credentials > OAuth client ID"
echo "   - Application type: Web application"
echo "   - Authorized redirect URIs:"
echo "     http://localhost:3205/api/auth/callback/google"
echo ""
echo "5. Copy your credentials to .env:"
echo "   GOOGLE_CLIENT_ID=your_client_id_here"
echo "   GOOGLE_CLIENT_SECRET=your_client_secret_here"
echo ""
echo "6. Restart the development server:"
echo "   npm run dev"
echo ""
echo "🎯 Special admin user: puladesign@gmail.com will be auto-assigned ADMIN role"
echo ""
echo "✅ Setup complete!"